### ISSUE TITLE
Crash when using

### ISSUE THREAD

**Issue by haf** [sanity-io/next-sanity#2013]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

When integrating the next-sanity library into a website, I'm getting this crash:

```
 ⨯ ./node_modules/.pnpm/@sanity+next-loader@1.2.0_@sanity+client@6.22.2_next@15.0.2_@babel+core@7.26.0_@opentelemetry_m74i26jrslokimmaeigdbmwjbm/node_modules/@sanity/next-loader/dist/_chunks-es/isCorsOriginError.js:1:1
Export CorsOriginError doesn't exist in target module
> 1 | import { CorsOriginError } from "@sanity/client";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | function isCorsOriginError(error) {
  3 |   return error instanceof CorsOriginError;
  4 | }

The export CorsOriginError was not found in module [project]/node_modules/.pnpm/@sanity+client@6.22.2/node_modules/@sanity/client/dist/index.browser.js [app-client] (ecmascript) <exports>.
Did you mean to import ServerError?
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.



./node_modules/.pnpm/@sanity+next-loader@1.2.0_@sanity+client@6.22.2_next@15.0.2_@babel+core@7.26.0_@opentelemetry_m74i26jrslokimmaeigdbmwjbm/node_modules/@sanity/next-loader/dist/_chunks-es/isCorsOriginError.js:1:1
Export CorsOriginError doesn't exist in target module
> 1 | import { CorsOriginError } from "@sanity/client";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | function isCorsOriginError(error) {
  3 |   return error instanceof CorsOriginError;
  4 | }

The export CorsOriginError was not found in module [project]/node_modules/.pnpm/@sanity+client@6.22.2/node_modules/@sanity/client/dist/index.js [app-ssr] (ecmascript) <exports>.
Did you mean to import ServerError?
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.
```

**To Reproduce**

Load a page

**Expected behavior**

Not to crash, and to provide a stack trace to help me understand where this crash is coming from originally

**Screenshots**
<img width="678" alt="image" src="https://github.com/user-attachments/assets/d9919176-ae4c-405a-89db-5b75261a38f5">

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

```
      next-sanity:
        specifier: ^9.8.20
        version: 9.8.20(@sanity/client@6.22.2)(@sanity/icons@3.4.0(react@18.3.1))(@sanity/types@3.65.1)(@sanity/ui@2.9.1(react-dom@18.3.1(react@18.3.1))(react-is@18.3.1)(react@18.3.1)(styled-components@6.1.13(react-dom@18.3.1(react@18.3.1))(react@18.3.1)))(next@15.0.2(@babel/core@7.26.0)(@opentelemetry/api@1.9.0)(react-dom@18.3.1(react@18.3.1))(react@18.3.1))(react-dom@18.3.1(react@18.3.1))(react@18.3.1)(sanity@3.65.1(@types/node@22.9.0)(@types/react@18.3.12)(react-dom@18.3.1(react@18.3.1))(react@18.3.1)(styled-components@6.1.13(react-dom@18.3.1(react@18.3.1))(react@18.3.1)))(styled-components@6.1.13(react-dom@18.3.1(react@18.3.1))(react@18.3.1))
      next:
        specifier: ^15.0.2
        version: 15.0.2(@babel/core@7.26.0)(@opentelemetry/api@1.9.0)(react-dom@18.3.1(react@18.3.1))(react@18.3.1)
```

**Additional context**

not really
